apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: attribute-recommendation-inference-u0003
  annotations:
    scenarios.ai.sap.com/description: "Attribute recommendation inference"
    scenarios.ai.sap.com/name: "attribute-recommendation-inference-scenario"
    executables.ai.sap.com/description: "Attribute recommendation inference executable"
    executables.ai.sap.com/name: "attribute-recommendation-inference-exec"
  labels:
    scenarios.ai.sap.com/id: "image-seg-tutorial"
    executables.ai.sap.com/id: "image-seg-infer-tutorial"
    ai.sap.com/version: "1.0.0"
spec:
  inputs:
    parameters: []
    artifacts:
      - name: attribute_recommendation_model
  template:
    apiVersion: "serving.kubeflow.org/v1beta1"
    metadata:
      labels: |
        ai.sap.com/resourcePlan: infer.s
    spec: |
      predictor:
        imagePullSecrets:
          - name: docker-registry-u0003
        containers:
        - name: kfserving-container
          image: "docker.io/kemperd/attribute-recommendation-infer:0.0.1"
          ports:
            - containerPort: 9001
              protocol: TCP
          env:
            - name: STORAGE_URI
              value: "{{inputs.artifacts.attribute_recommendation_model}}"
